apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-udagram-env
data:
  credentials: |
    [default]
    aws_access_key_id=AKIA53RIKLYSHFJCV4FX
    aws_secret_access_key=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
